### ISSUE TITLE
Proposition: psf fonts

### ISSUE THREAD

**Issue by ghost** [nbyouri/moddedfonts#1]
Hi!

Venam said to me that you had good fonts, and so they are.

If you ever want to produce .psf fonts for use in tty, I can help you with that.  I made firsts versions [here](http://gihub.com/sshbio/moddedfonts), but they lack some important characters like the box drawing characters.

Tell me if you ever need those

Glad to discover these fonts!

**Comment by nbyouri** [comment]
Hello,

I don't have a Linux install handy to test, but I'm certainly willing to merge a pull request containing the working fonts. Glad you like them and thanks for working on that!

**Comment by ghost** [comment]
Oh, noes!  Not a problem, I'll add the missing characters and I'll make a pull request.

Do you prefer 2px or 1px for the thickness of the strokes of the box drawing characters?

```
─┌├┬...
```

**Comment by nbyouri** [comment]
1px sounds good

**Comment by ghost** [comment]
Let's go!

**Comment by nbyouri** [comment]
Merged, thanks!
